language: python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libasound2-dev portaudio19-dev python-pyaudio python3-pyaudio
  - pip install pytest-mock

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest -vs tests
